services:
  web:
    build: .
    networks:
      - traefik_default
    environment:
      - DATABASE_URL=postgresql://postgres:Souumbbk1@185.209.230.133:5432/tax
      - MONGO_URL=mongodb://admin:%40Souumbbk1@185.209.230.133:27017
    labels:
      - traefik.enable=true
      - traefik.http.routers.cod-rastreio-development-2312.rule=Host(`webhook.rastreou.org`)
      - traefik.http.routers.cod-rastreio-development-2312.entrypoints=websecure
      - traefik.http.routers.cod-rastreio-development-2312.middlewares=cors-cod-rastreio-development-2312@docker
      - traefik.http.routers.cod-rastreio-development-2312.tls.certresolver=letsencrypt
      - traefik.http.routers.cod-rastreio-development-2312.service=cod-rastreio-development-2312
      - traefik.http.services.cod-rastreio-development-2312.loadbalancer.server.port=3000
      - traefik.http.middlewares.cors-cod-rastreio-development-2312.headers.customResponseHeaders.access-control-allow-origin=*
      - traefik.http.middlewares.cors-cod-rastreio-development-2312.headers.customResponseHeaders.access-control-allow-credentials=true
    restart: "always"
    
networks:
  traefik_default:
    external: true